# docker build -t hongs/hongs-jdk:8 .
# docker run hongs/hongs-jdk:8

FROM ubuntu:16.04

MAINTAINER Kevin Hongs <kevin.hongs@gmail.com>

ADD jdk-8u131-linux-x64.tar.gz /opt/

ENV JAVA_HOME /opt/jdk1.8.0_131
