
bootstrap.servers=master:9092,slave1:9092,slave2:9092
acks=all
retries=0
batch.size=16384
key.serializer=org.apache.kafka.common.serialization
value.serializer=org.apache.kafka.common.serialization

masync.diffuse.topic=masync.diffuse.
